### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by WorshipMeOrElse** [Reselim/Flipper#22]
the documentation link in the github page seems to be broken. the start screen works but once I enter into the documentation it shows the screenshot

![image](https://user-images.githubusercontent.com/79610974/201977382-40fa0969-e586-4c0f-8513-91e69132bf7f.png)

**Comment by Reselim** [comment]
Page doesn't exist yet, this is intentional. I haven't gotten around to writing full docs for Flipper and I don't know if I ever will.
